vich_uploader:
    db_driver: orm
    mappings:
        films_images:
            uri_prefix: '%films_images%'
            upload_destination: '%kernel.project_dir%/public%films_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true